export const db = {
  courses: [
    {
      id: 1,
      user: 'Miguel Ángel Durán',
      completedTasks: 20,
      totalTasks: 35,
      userCount: 10,
      note: 35,
      view: 100,
      time: '12h 30m',
      courseTitle: 'Aprende los fundamentos de Next.js desde cero.',
      desc: 'Este curso cubre los conceptos basicos de Next.js',
      tags: 'Web',
      rating: 4.9,
      ratingCount: 9
    },
    {
      id: 2,
      user: 'Miguel Ángel Durán',
      completedTasks: 25,
      totalTasks: 46,
      userCount: 20,
      note: 46,
      view: 1200,
      time: '10h 15m',
      courseTitle: 'Curso avanzado de React con Hooks y Context.',
      desc: 'Aprende a dominar hooks y el contexto global en React',
      tags: 'Web',
      rating: 3.5,
      ratingCount: 5
    },
    {
      id: 3,
      user: 'Traversy Media',
      completedTasks: 19,
      totalTasks: 44,
      userCount: 12,
      note: 15,
      view: 500,
      time: '48h',
      courseTitle: 'Fundamentos de diseño web con HTML y CSS.',
      desc: 'Aprende a crear páginas web atractivas y responsivas.',
      tags: 'Design',
      rating: 4.5,
      ratingCount: 8
    },
    {
      id: 4,
      user: 'Free Code Camp',
      completedTasks: 26,
      totalTasks: 53,
      userCount: 15,
      note: 14,
      view: 420,
      time: '76h 20m',
      courseTitle: 'Curso completo de desarrollo web full-stack.',
      desc: 'Aprende a construir aplicaciones web completas con frontend y backend',
      tags: 'Web',
      rating: 5.0,
      ratingCount: 15
    },
    {
      id: 5,
      user: 'Josh Starmer',
      completedTasks: 15,
      totalTasks: 24,
      userCount: 23,
      note: 35,
      view: 780,
      time: '10h 25m',
      courseTitle: 'Introducción a la inteligencia artificial y machine learning',
      desc: 'Descubre los conocimientos basicos de la inteligencia artificial.',
      tags: 'AI',
      rating: 3.9,
      ratingCount: 45
    },
    {
      id: 6,
      user: 'Felipe Vergara',
      completedTasks: 14,
      totalTasks: 50,
      userCount: 54,
      note: 34,
      view: 245,
      time: '31h',
      courseTitle: 'Curso de fundamentos de marketing digital.',
      desc: 'Aprender las estrategias clave del marketing digital.',
      tags: 'Marketing',
      rating: 2.6,
      ratingCount: 15
    },
    {
      id: 7,
      user: 'Hixec',
      completedTasks: 24,
      totalTasks: 62,
      userCount: 42,
      note: 53,
      view: 243,
      time: '21h',
      courseTitle: 'Curso de introducción a la ciberseguridad.',
      desc: 'Aprende los conceptos basicos de la ciberseguridad.',
      tags: 'Web',
      rating: 4.5,
      ratingCount: 12
    },
    {
      id: 8,
      user: 'Miguel Ángel Durán',
      completedTasks: 18,
      totalTasks: 24,
      userCount: 30,
      note: 40,
      view: 360,
      time: '15h 30m',
      courseTitle: 'Curso de introducción a la nube con AWS.',
      desc: 'Aprende los conceptos básicos de la computación en la nube.',
      tags: 'Web',
      rating: 4.0,
      ratingCount: 10
    },
    {
      id: 9,
      user: 'Traversy Media',
      completedTasks: 22,
      totalTasks: 65,
      userCount: 25,
      note: 42,
      view: 500,
      time: '18h',
      courseTitle: 'Fundamentos de desarrollo móvil con React Native.',
      desc: 'Aprende a crear aplicaciones móviles multiplataforma.',
      tags: 'Web',
      rating: 4.3,
      ratingCount: 14
    },
    {
      id: 10,
      user: 'Dalto',
      completedTasks: 12,
      totalTasks: 14,
      userCount: 15,
      note: 30,
      view: 180,
      time: '12h',
      courseTitle: 'Curso de introducción al diseño UX/UI.',
      desc: 'Aprende los principios básicos del diseño UX/UI.',
      tags: 'Design',
      rating: 4.1,
      ratingCount: 8
    },
    {
      id: 11,
      user: 'Free Code Camp',
      completedTasks: 20,
      totalTasks: 56,
      userCount: 22,
      note: 38,
      view: 400,
      time: '20h 30m',
      courseTitle: 'Curso de introducción a la programación con Python.',
      desc: 'Aprende los conceptos básicos de la programación usando Python.',
      tags: 'Programming',
      rating: 4.7,
      ratingCount: 12
    },
    {
      id: 12,
      user: 'Jon',
      completedTasks: 10,
      totalTasks: 51,
      userCount: 12,
      note: 25,
      view: 150,
      time: '8h 15m',
      courseTitle: 'Curso de introducción a la analítica de datos con Excel.',
      desc: 'Aprende a analizar datos de manera efectiva usando Microsoft Excel.',
      tags: 'Marketing',
      rating: 4.0,
      ratingCount: 6
    },
    {
      id: 13,
      user: 'Mark Shead',
      completedTasks: 14,
      totalTasks: 56,
      userCount: 16,
      note: 28,
      view: 200,
      time: '9h 45m',
      courseTitle: 'Curso de introducción a la gestión de proyectos en Agile.',
      desc: 'Aprende los principios y prácticas de la gestión de proyectos Agile.',
      tags: 'Programming',
      rating: 4.2,
      ratingCount: 7
    },
    {
      id: 14,
      user: 'Simply Explained',
      completedTasks: 8,
      totalTasks: 10,
      userCount: 10,
      note: 22,
      view: 120,
      time: '5h 30m',
      courseTitle: 'Curso de fundamentos de blockchain y criptomonedas.',
      desc: 'Aprende los conceptos básicos de blockchain y criptomonedas.',
      tags: 'Programming',
      rating: 4.6,
      ratingCount: 9
    },
    {
      id: 15,
      user: 'Felipe Vergara',
      completedTasks: 11,
      totalTasks: 77,
      userCount: 12,
      note: 27,
      view: 140,
      time: '6h 10m',
      courseTitle: 'Curso de introducción a la realidad aumentada y virtual.',
      desc: 'Aprende los conceptos básicos de AR y VR.',
      tags: 'AI',
      rating: 4.3,
      ratingCount: 8
    },
    {
      id: 16,
      user: 'Fazt Code',
      completedTasks: 13,
      totalTasks: 14,
      userCount: 14,
      note: 32,
      view: 160,
      time: '7h 20m',
      courseTitle: 'Curso de fundamentos de DevOps y CI/CD.',
      desc: 'Aprende los principios y prácticas de DevOps, integración continua y entrega continua.',
      tags: 'DevOps',
      rating: 4.5,
      ratingCount: 10
    },
    {
      id: 17,
      user: 'edureka!',
      completedTasks: 9,
      totalTasks: 10,
      userCount: 10,
      note: 21,
      view: 90,
      time: '10h 30m',
      courseTitle: 'Curso de introducción a la automatización con RPA.',
      desc: 'Aprende los conceptos básicos de RPA.',
      tags: 'Programming',
      rating: 4.1,
      ratingCount: 5
    },
    {
      id: 18,
      user: 'Freddy Vega',
      completedTasks: 16,
      totalTasks: 18,
      userCount: 18,
      note: 34,
      view: 200,
      time: '15h 4m',
      courseTitle: 'Curso de fundamentos de Internet de las Cosas (IoT).',
      desc: 'Aprende los conceptos básicos de IoT.',
      tags: 'AI',
      rating: 4.4,
      ratingCount: 7
    },
    {
      id: 19,
      user: 'Hixec',
      completedTasks: 7,
      totalTasks: 10,
      userCount: 8,
      note: 18,
      view: 70,
      time: '1h 50m',
      courseTitle: 'Virtualización en VirtualBox.',
      desc: 'Aprende a crear y gestionar máquinas virtuales usando VirtualBox.',
      tags: 'Programming',
      rating: 4.0,
      ratingCount: 4
    },
    {
      id: 20,
      user: 'Mosh Hamedani',
      completedTasks: 12,
      totalTasks: 15,
      userCount: 14,
      note: 29,
      view: 160,
      time: '45m 16s',
      courseTitle: 'Curso de la introducción a la programación JavaScript',
      desc: 'Aprende los conceptos basicos de la programación usando JavaScript',
      tags: 'Programming',
      rating: 4.2,
      ratingCount: 6
    },
    {
      id: 21,
      user: 'Free Code Camp',
      completedTasks: 18,
      totalTasks: 90,
      userCount: 22,
      note: 38,
      view: 300,
      time: '12h',
      courseTitle: 'Curso de la introducción a la programación con Ruby.',
      desc: 'Aprende los conceptos basicos de la programación usando Ruby.',
      tags: 'Programming',
      rating: 4.7,
      ratingCount: 11
    },
    {
      id: 22,
      user: 'Hixec',
      completedTasks: 14,
      totalTasks: 31,
      userCount: 18,
      note: 32,
      view: 180,
      time: '10h 20m',
      courseTitle: 'Curso de introducción a la programación con Angular.',
      desc: 'Aprende los conceptos basicos y avanzados de la programación usando Angular.',
      tags: 'Web',
      rating: 4.4,
      ratingCount: 9
    },
    {
      id: 23,
      user: 'Oscar Turquet',
      completedTasks: 20,
      totalTasks: 45,
      userCount: 98,
      note: 4.6,
      view: 250,
      time: '1h 2m 13s',
      courseTitle: 'Curso de introducción a la programación con Go.',
      desc: 'Aprende los conceptos básicos y avanzados de la programación usando Go.',
      tags: 'Programming',
      rating: 4.6,
      ratingCount: 10,
      instructor: 'Oscar Turquet'
    },
    {
      id: 24,
      user: 'Free Code Camp',
      completedTasks: 22,
      totalTasks: 25,
      userCount: 28,
      note: 48,
      view: 300,
      time: '20h 10m',
      courseTitle: 'Curso de MongoDB para desarrolladores.',
      desc: 'Aprende los conceptos desde el más básico al más avanzado utilizando MongoDB.',
      tags: 'Web',
      rating: 4.8,
      ratingCount: 12
    }
  ]
};
